### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by VanessaAoki** [jonathastavares/authentication#2]
Hey Jonathas, great project!

I can see that you are trying to use a Ruby linter in your workflows `tests.yml`. 
> For rails you should only have 'linters.yml', as shown in [Microverse's RoR linters](https://github.com/microverseinc/linters-config/tree/master/ror/.github/workflows).

Keep up the good work!

**Comment by jonathastavares** [comment]
Thank you @VanessaAoki ! I removed the tests.yml file.
